### ISSUE TITLE
Make The Need To Scroll Obvious

### ISSUE THREAD

**Issue by rjriel** [QlikHackathon/decode-oct-2017#1]
When you first get to the page, there isn't really and indication that you should scroll down. Some sort of visual indication that the user should scroll to access more would be great

**Comment by MelisaIm** [comment]
Would like to work on this

**Comment by rjriel** [comment]
Hey @MelisaIm,

Thanks so much for your interest, we're super excited to see external interest in this project.

At this point in time we're not really looking to get external help. This project is a result of our local [deCODE Hackathon](http://hackdecode.io/) and we are actually in line to present the results to a representative of the United Nations at the end of the week, so right now we're giving our team from the hackathon an opportunity to make some small changes that we had previously discussed.

Once that presentation happens and we publish the project to [Qlik Playground](http://playground.qlik.com/showcase), we'll definitely start taking pull requests from the outside world.
